name: BTest

on:
  pull_request:
  push:
    branches: [master]

jobs:
  Run-BTest:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up git config
        # Set autocrlf mode to false so that actions/checkout doesn't
        # modify the line endings in all of the files (mostly in the
        # test Baselines) to be \r\n on Windows.
        run: |
            git config --global core.autocrlf false
            git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install sphinx
      - run: make test

  Test-SetupPY:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: "Install pip and the btest package"
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install setuptools wheel
            python3 -m pip install .
      - name: "Run btests with installed version"
        run: |
            cd testing
            which btest
            make
      - name: "Test building package"
        run: |
            python3 setup.py sdist bdist_wheel
